config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
      get 'users/', to: 'devise/sessions#new'
  end

  authenticated :user do
    root 'home#index', as: :authenticated_root
  end
  devise_scope :user do
    root :to => "devise/sessions#new"
  end
  resources :posts
  resources :comments, only: [:create, :destroy]
  resources :users do
    member do
      get :friends
      get :followers
      get :deactivate
      get :mentionable
    end
  end

  resources :events do
    collection do
      get :calendar
    end
  end

  match :follow, to: 'follows#create', as: :follow, via: :post
  match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post
  match :like, to: 'likes#create', as: :like, via: :post
  match :unlike, to: 'likes#destroy', as: :unlike, via: :post
  match :find_friends, to: 'home#find_friends', as: :find_friends, via: :get
  match :about, to: 'home#about', as: :about, via: :get

  get 'home/front'
  get 'home/donate'

end

app/models/concerns/shared/callbacks.rb
# Copyright (c) 2015, @sudharti(Sudharsanan Muralidharan)
# Socify is an Open source Social network written in Ruby on Rails This file is licensed
# under GNU GPL v2 or later. See the LICENSE.

module Shared::Callbacks
  extend ActiveSupport::Concern

  included do
    before_destroy :remove_activity
    before_destroy :remove_likes
  end

  def remove_activity
    activity = PublicActivity::Activity.find_by(trackable_id: self.id, trackable_type: self.class.to_s, key: "#{self.class.to_s.downcase}.create")
    activity.destroy if activity.present?
    true
  end

  def remove_likes
    activity = PublicActivity::Activity.find_by(trackable_id: self.id, trackable_type: self.class.to_s, key: "#{self.class.to_s.downcase}.like")
    activity.destroy if activity.present?
  end

end

app/views/shared/_actions.html.erb
<% if user_signed_in? %>
  <div class="actions">
    <div class="row">
      <div class="col-xs-6 like">
        <%= render 'likes/form', likeable: resource %>
      </div>
      <div class="col-xs-6 comment">
        <%= link_to resource, class: 'btn btn-block' do %>
          <%= fa_icon 'comment' %> comment
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_activity.html.erb
<%= render_activity(activity) %>

app/views/shared/_avatar.html.erb
<% if user %>
  <%= link_to user_path(user) do %>
    <%= image_tag user.avatar.url || 'avatar.jpg',class: "profile-photo ",alt: "user" %>
  <% end %>
<% end %>

app/views/shared/_cover.html.erb
<% if user.cover.url %>
  <div class="cover" style="background-image: url(<%= user.cover.url %>);"></div>
<% else %>
  <div class="cover" style="background-image: url(/assets/cover.png);"></div>
<% end %>

app/views/shared/_created_at.html.erb
<div class="created-at">
  <%= fa_icon 'clock-o' %>
  <%= relative_time(activity.created_at) %> ago
</div>

app/views/shared/_disqus.html.erb
<div class="col-md-4 static">

  <div class="card well">
    <img class="card-img-top img-responsive rounded" src="/images/children.jpg" alt="Card image cap">
    <div class="card-body text-justify">
      <h5 class="card-title">Pourquoi faire un don</h5>
      <p class="card-text">
        Il ne vous reste plus qu’à inviter, par tous les moyens (téléphone, mail, Facebook…), vos amis, vos
        relations, vos collègues à consulter cette page. Ils pourront y faire leurs dons en ligne, sur un site
        complètement sécurisé, et recevoir leur reçu fiscal.
      </p>
      <center>
        <a href="/home/donate" class="btn btn-primary ">Faire un Don</a>
      </center>
    </div>

  </div>
  <div id="disqus_thread"></div>
  <script>
    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
    /*
    var disqus_config = function () {
    this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    (function () { // DON'T EDIT BELOW THIS LINE
      var d = document,
        s = d.createElement('script');
      s.src = 'https://test-va5fupeos5.disqus.com/embed.js';
      s.setAttribute('data-timestamp', +new Date());
      (d.head || d.body).appendChild(s);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by
      Disqus.</a></noscript>

  <hr>

  <div class="card">
    <!-- <img class="card-img-top img-responsive" src="/images/children.jpg" alt="Card image cap"> -->
    <div class="card-body text-center">
      <!-- <h5 class="card-title">Pourquoi faire un don</h5> -->
      <p class="small">
        <a href="/">Acceuil</a>
        <a href="/home/front">Actualités</a>
        <a href="/home/donate">Donation</a>
        <a href="" class="smile">A Propos</a>
        <a href="" class="">Contact</a>
        <a href="" class="">Nous Supporter</a>
        <br>
        <p>&copy;copyright SaynaStudents 2019</p>
      </p>
      <!-- <a href="#" class="btn btn-primary">Faire un Don</a> -->

    </div>
  </div>

</div>

app/views/shared/_links.html.erb
<div id="links" class="well">
  <h5>
    <%= fa_icon 'newspaper-o' %>
    <%= link_to 'NewsFeed', root_path %>
  </h5>
  <h5>
    <%= fa_icon 'calendar-o' %>
    <%= link_to 'Create Event', new_event_path %>
  </h5>
  <h5>
    <%= fa_icon 'calendar-o' %>
    <%= link_to 'Events Calendar', calendar_events_path %>
  </h5>
  <h5>
    <%= fa_icon 'arrow-circle-right' %>
    <%= link_to 'Friends', friends_user_path(current_user) %>
  </h5>
  <h5>
    <%= fa_icon 'arrow-circle-left' %>
    <%= link_to 'Followers', followers_user_path(current_user) %>
  </h5>
  <h5>
    <%= fa_icon 'search' %>
    <%= link_to('Find Friends', find_friends_path)%>
  </h5>
  <h5>
    <%= fa_icon 'pencil' %>
    <%= link_to 'Edit Profile', edit_user_path(current_user) %>
  </h5>
  <h5>
    <%= fa_icon 'lock' %>
    <%= link_to 'Change password', edit_user_registration_path %>
  </h5>
</div>

app/views/shared/_navbar.html.erb
<header id="header">
  <nav class="navbar navbar-default navbar-fixed-top menu">
    <div class="container">

      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
          aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"><img src="/images/logo.png" alt="logo" /></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right main-menu">

          <li class="dropdown"><a href="/">Accueil</a></li>
          <li class="dropdown"><a href="/home/front">Actualité</a></li>
          <!-- <li class="dropdown"><a href="contact.html">A propos</a></li> -->
          <% if user_signed_in? %>

          <li class="dropdown">

            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Connexion
              <span><img src="/images/down-arrow.png" alt="" /></span></a>
            <ul class="dropdown-menu newsfeed-home">



              <li>
                <%= link_to('Profile', user_path(current_user)) %>
              </li>
              <li>
                <%= link_to 'Modifier Profile', edit_user_path(current_user) %>
              </li>
              <li>
                <%= link_to 'Modifier Mot de passe', edit_user_registration_path %>
              </li>
              <li>
                <%= link_to('Déconnexion', destroy_user_session_path, method: :delete) %>
              </li>
            </ul>


          </li>




          <% else %>
          <li class="dropdown">

            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Connexion
              <span><img src="/images/down-arrow.png" alt="" /></span></a>
            <ul class="dropdown-menu newsfeed-home text-center" >
              <li>
                <%= link_to 'Devenez membre', new_user_registration_path %>
              </li>

              <li>
                <%= link_to 'Se Connecter', user_session_path%>
              </li>

            </ul>


          </li>

          <% end %>
          <!-- <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Home <span><img src="/images/down-arrow.png" alt="" /></span></a>
                  <ul class="dropdown-menu newsfeed-home">
                    <li><a href="index.html">Landing Page 1</a></li>
                    <li><a href="index-register.html">Landing Page 2</a></li>
                  </ul>
              </li> -->

        </ul>
        <!-- <form class="navbar-form navbar-right hidden-sm">
          <div class="form-group">
            <i class="icon ion-android-search"></i>
            <input type="text" class="form-control" placeholder="Search friends, photos, videos">
          </div>
        </form> -->
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container -->
  </nav>
</header>

<script src="/js/bootstrap.min.js"></script>
<script src="/js/jquery.appear.min.js"></script>
<script src="/js/jquery.incremental-counter.js"></script>
<script src="/js/script.js"></script>

app/views/shared/_no_resource.html.erb
<div class="no-resource text-center">
  <h5>No <%= resources %> found.</h5>
</div>

app/views/shared/_paginate.html.erb
<div id="endless-scroll" class="well text-center hidden">
  <%= image_tag 'ajax-loader.gif' %>
  <%= will_paginate resources %>
</div>

app/views/shared/_paginate.js.erb
<% if resources.next_page %>
  $(".pagination").replaceWith("<%= j will_paginate(resources) %>");
  $(".pagination").hide();
<% else %>
  $(window).off('scroll');
  $("#endless-scroll").remove();
<% end %>

app/views/shared/_user_info.html.erb
<!-- <div id="user-info" class="well">
  <div class="text-center">
    <%= render 'shared/avatar', user: @user %><br>
    <h5><%= link_to @user.name, @user %></h5>
  </div>
  <h5>
    <%= fa_icon 'shield' %>
    <%= pluralize(@user.posts_count, 'post') %>
  </h5>
  <% if @user.dob.present? %>
    <h5>
      <%= fa_icon @user.sex %>
      <%= "#{pluralize(age(@user.dob), 'year')} old" %>
    </h5>
  <% end %>
  <% if @user.location.present? %>
    <h5>
      <%= fa_icon 'map-marker' %>
      <%= @user.location %>
    </h5>
  <% end %>
  <h5>
    <i class="icon-record"></i> <%= pluralize(@user.points, 'point') %>
  </h5>
  <% if @user.badges.empty? %>
    <h5>No badge yet.</h5>
  <% else %>
    <h5>
      <% @user.badges.each do |badge| %>
        <i class="<%= badge.custom_fields[:icon] %>" style="color: <%= badge.custom_fields[:color] %>">
        </i>
        <%= badge.name %>
      <% end %>
    </h5>
  <% end %>
  <br>
  <div class="text-center">
    <% unless is_current_user?(@user) %>
      <%= render 'follows/form', user: @user %>
      <h6><%= 'Follows you' if current_user.followed_by?(@user) %></h6>
    <% end %>
  </div>
</div> -->

<div class="profile-card">


  <%= render 'shared/avatar', user: @user %>
  <h5>
    <%= link_to @user.name, @user , class: "text-white"%>

  </h5>

</div>


<!--profile card ends-->
<div id="links" class="well">
<ul class="nav-news-feed">
  <li><i class="icon ion-ios-paper"></i>
    <%= link_to 'Actualité', root_path %>
  </li>
  <li><i class="ion-android-favorite-outline  "></i>
    <%= link_to 'Crée des événements', new_event_path %>
  </li>
  <li><i class=" icon ion-ios-calendar"></i>
    <%= link_to 'Liste des évenements ', calendar_events_path %>
  </li>
  <li><i class="icon ion-ios-people"></i>
    <%= link_to 'Amis', friends_user_path(current_user) %>
  </li>
  <li><i class="icon ion-ios-people-outline"></i>
    <%= link_to 'Followers', followers_user_path(current_user) %>
  </li>
  <li><i class="icon ion-ios-search"></i>
    <%= link_to('Trouver des personnes', find_friends_path)%>
  </li>
  <li><i class="icon ion-edit"></i>
    <%= link_to 'Modifier Profil', edit_user_path(current_user) %>
  </li>
  <li><i class="ion-ios-locked-outline"></i>
    <%= link_to 'Changer mot de passe', edit_user_registration_path %>
  </li>
</ul>
</div>
<!--news-feed links ends-->
<!-- <div id="chat-block">
  <div class="title">Chat online</div>
  <ul class="online-users list-inline">
    <li><a href="newsfeed-messages.html" title="Linda Lohan"><img src="images/users/user-2.jpg" alt="user" class="img-responsive profile-photo" /><span
          class="online-dot"></span></a></li>
    <li><a href="newsfeed-messages.html" title="Sophia Lee"><img src="images/users/user-3.jpg" alt="user" class="img-responsive profile-photo" /><span
          class="online-dot"></span></a></li>
    <li><a href="newsfeed-messages.html" title="John Doe"><img src="images/users/user-4.jpg" alt="user" class="img-responsive profile-photo" /><span
          class="online-dot"></span></a></li>
    <li><a href="newsfeed-messages.html" title="Alexis Clark"><img src="images/users/user-5.jpg" alt="user" class="img-responsive profile-photo" /><span
          class="online-dot"></span></a></li>
    <li><a href="newsfeed-messages.html" title="James Carter"><img src="images/users/user-6.jpg" alt="user" class="img-responsive profile-photo" /><span
          class="online-dot"></span></a></li>
    <li><a href="newsfeed-messages.html" title="Robert Cook"><img src="images/users/user-7.jpg" alt="user" class="img-responsive profile-photo" /><span
          class="online-dot"></span></a></li>
    <li><a href="newsfeed-messages.html" title="Richard Bell"><img src="images/users/user-8.jpg" alt="user" class="img-responsive profile-photo" /><span
          class="online-dot"></span></a></li>
    <li><a href="newsfeed-messages.html" title="Anna Young"><img src="images/users/user-9.jpg" alt="user" class="img-responsive profile-photo" /><span
          class="online-dot"></span></a></li>
    <li><a href="newsfeed-messages.html" title="Julia Cox"><img src="images/users/user-10.jpg" alt="user" class="img-responsive profile-photo" /><span
          class="online-dot"></span></a></li>
  </ul>
</div> -->
<!--chat block ends-->